name: Android CI with Ant

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
  
    - name: Build the application
      run: |
        cd linearlauncher
        ant debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: linearlauncher-debug-apk
        path: linearlauncher/bin/*-debug.apk
